#ifndef NETTYPEMESSAGEID_H
#define NETTYPEMESSAGEID_H

enum NetTypeMessageId
{
	ID_NEW_INCOMING_CONNECTION,
	ID_CONNECTION_LOST,
	ID_DISCONNECTION_NOTIFICATION,
	ID_CONNECTION_REQUEST_ACCEPTED,
	ID_REMOTE_NEW_INCOMING_CONNECTION,
	ID_REMOTE_CONNECTION_LOST,
	ID_REMOTE_DISCONNECTION_NOTIFICATION,
	ID_ALREADY_CONNECTED,
	ID_CONNECTION_BANNED,
	ID_NO_FREE_INCOMING_CONNECTIONS,
	ID_CONNECTION_ATTEMPT_FAILED,
	ID_INVALID_PASSWORD,
	ID_USER_PACKET
};


#endif